apiVersion: v1
kind: Service
metadata:
  name: e-mission-landing
  namespace: e-mission-landing
spec:
  selector:
    app: e-mission-landing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
